apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
  labels:
    app: fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher
  template:
    metadata:
      labels:
        app: fetcher
    spec:
      containers:
      - name: fetcher
        image: newsagg-fetcher:v0.4
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret-uri
              key: RABBITMQ_URI
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
